require("core.options")
require("core.keymaps").init()

-- Plugins
require("plugins.packer")
require("plugins.autocommands")
require("plugins.colorscheme")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.impatient")
require("plugins.indentline")
require("plugins.lsp")
require("plugins.null-ls")
require("plugins.lspsaga")
